### ISSUE TITLE
Not sure if the Jarvis module works.

### ISSUE THREAD

**Issue by Marlee-True** [nitrix/senko#2]
Every single time I use the Jarvis module the audio ques will play but nothing seems to happen I've only recently invited the bot and its not very significant of a downside just a bug that is easy to forget about. also id like to mention that the bot overall works very well and I commend you for the job well done!

**Comment by nitrix** [comment]
I think the speech-to-text that its using (it's a Google Cloud service) is the problem.

I want to rewrite the bot, it would be a good opportunity to make sure it can work completely on its own, without third party providers. The keyword detection for example works nicely (it's using Porcupine) and I know the same company has a Speech-to-Text product too that works offline. Worth looking into.

I'll let you know when things have improved :)
